name: Python Environment Setup
description: Set up Python environment
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v4.2.2
    - name: setup the python environment
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt